export const NormSchema = {
  tableName: "norms",
  fieldList: {
    normId: {
      label: "",
      name: "",
      placeholder: "",
      description: "",
      inputType: "",
      dataType: "NUMBER",
      columnName: "normId",
      db: true,
      pk: true,
      form: true,
      required: false,
    },
    normDescription: {
      label: "Description",
      name: "normDescription",
      placeholder: "Description",
      description: "",
      inputType: "text",
      dataType: "STRING",
      columnName: "normDescription",
      db: true,
      form: true,
      required: true,
      default: "norm de",
    },
    qty: {
      label: "Qty",
      name: "qty",
      placeholder: "Qty",
      description: "",
      inputType: "text",
      dataType: "STRING",
      columnName: "qty",
      db: true,
      form: true,
      required: true,
      default: 100,
    },
    unit: {
      label: "Unit",
      name: "unit",
      placeholder: "Unit",
      description: "",
      inputType: "text",
      dataType: "STRING",
      columnName: "unit",
      db: true,
      form: true,
      required: true,
      default: "m2",
    },
  },
};
