const NormMaterialDetailsSchema = {
  tableName: "norm-material-details",
  fieldList: {
    normMaterialDetailId: {
      label: "",
      name: "normMaterialDetailId",
      placeholder: "",
      description: "",
      inputType: "number",
      dataType: "NUMBER",
      columnName: "normMaterialDetailId",
      db: true,
      pk: true,
      form: true,
      required: false,
      default: 0,
    },
    normId: {
      label: "",
      name: "normId",
      placeholder: "",
      description: "",
      inputType: "number",
      dataType: "NUMBER",
      columnName: "normId",
      db: true,
      form: true,
      required: false,
      default: 0,
    },
    itemName: {
      label: "Item Name",
      name: "itemName",
      placeholder: "Item Name",
      description: "",
      inputType: "text",
      dataType: "STRING",
      columnName: "itemName",
      db: false,
      form: true,
      required: true,
      default: "itemName",
    },
    qty: {
      label: "Qty",
      name: "qty",
      placeholder: "Qty",
      description: "",
      inputType: "number",
      dataType: "NUMBER",
      columnName: "qty",
      db: true,
      form: true,
      required: true,
      default: 100,
    },
    unit: {
      label: "Unit",
      name: "unit",
      placeholder: "Unit",
      description: "",
      inputType: "text",
      dataType: "STRING",
      columnName: "unit",
      db: true,
      form: true,
      required: true,
      default: "m2",
    },
  },
};

export const NormSchema = {
  tableName: "norms",
  fieldList: {
    normId: {
      label: "Norm Id",
      name: "normId",
      placeholder: "Norm Id",
      description: "",
      inputType: "number",
      dataType: "NUMBER",
      columnName: "normId",
      db: true,
      pk: true,
      form: true,
      required: false,
      default: 0,
      disabled: true,
    },
    normDescription: {
      label: "Description",
      name: "normDescription",
      placeholder: "Description",
      description: "",
      inputType: "text",
      dataType: "STRING",
      columnName: "normDescription",
      db: true,
      form: true,
      required: true,
      default: "norm de",
    },
    qty: {
      label: "Qty",
      name: "qty",
      placeholder: "Qty",
      description: "",
      inputType: "number",
      dataType: "NUMBER",
      columnName: "qty",
      db: true,
      form: true,
      required: true,
      default: 100,
    },
    unit: {
      label: "Unit",
      name: "unit",
      placeholder: "Unit",
      description: "",
      inputType: "text",
      dataType: "STRING",
      columnName: "unit",
      db: true,
      form: true,
      required: true,
      default: "m2",
    },
    materials: {
      name: "materials",
      inputType: "array",
      dataType: "ARRAY",
      subSchema: NormMaterialDetailsSchema,
      columnName: "materials",
    },
  },
};

// const CartSchema = {
//   tableName: "carts",
//   fieldList: {
//     desc: {
//       label: "desc",
//       name: "desc",
//       placeholder: "desc",
//       description: "",
//       inputType: "text",
//       dataType: "STRING",
//       columnName: "desc",
//       db: true,
//       form: true,
//       required: false,
//       default: "amountamount",
//     },
//     amount: {
//       label: "amount",
//       name: "amount",
//       placeholder: "amount",
//       description: "",
//       inputType: "text",
//       dataType: "STRING",
//       columnName: "amount",
//       db: true,
//       form: true,
//       required: true,
//       default: "amountamount",
//     },
//   },
// };
